version:  "3.7"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=slim_test

  test:
    build: .
    environment: 
      - REDIS_URL=redis://redis_db:6379
      - DATABASE_URL=postgres://user:password@db/slim_test
      - CRYSTAL_ENV=production
      - PORT=4000
      - HOST=slim
      - CRYSTAL_WORKERS=1
      - LOG_LEVEL=debug
      - DB_POOL_SIZE=1
    command: bash -c "shards install && crystal spec spec/acceptance"
    ports:
      - "4001:4001"
    depends_on:
      - slim
    volumes:
      - .:/app

  slim:
    build: .
    environment: 
      - REDIS_URL=redis://redis_db:6379
      - DATABASE_URL=postgres://user:password@db/slim_test
      - CRYSTAL_ENV=production
      - CRYSTAL_WORKERS=1
      - LOG_LEVEL=info
      - PORT=4000
      - HOST=localhost
      - DB_POOL_SIZE=1
    command: bash -c "make clean build migrate run"
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - db
      