apiVersion: v1
kind: Service
metadata:
  name: slim-api-service
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: slim-api

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slim-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: slim-api
  template:
    metadata:
      labels:
        app: slim-api
    spec:
      containers:
        - name: slim
          image: registry.gitlab.com/eliasjpr/slim:latest
        imagePullSecrets:
        - name: regcred
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"
            - name: HOST
              value: "0.0.0.0"
            - name: CRYSTAL_WORKERS
              value: "2"
            - name: DB_POOL_SIZE 
              value: "6"
            - name: CRYSTAL_ENV
              value: production
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: databaseurl
                  key: DATABASE_URL

